import { SITE_NAME } from '@/constants/seo-constants'
import type { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: { default: SITE_NAME, template: `%s | ${SITE_NAME}` },
  description: 'Generated by create next app',
}

export default function Layout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div>{children}</div>
      </body>
    </html>
  )
}
