import { SITE_NAME } from '@/constants/seo-constants'
import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import './globals.scss'

const jetbrainsMono = JetBrains_Mono({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  style: 'normal',
  variable: '--font-jetbrainsMono',
})

export const metadata: Metadata = {
  title: {default: SITE_NAME, template: `%s | ${SITE_NAME}`},
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={jetbrainsMono.className}>{children}</body>
    </html>
  )
}
